import KelasImage1 from "./assets/img/kelas/kelas-1.jpg";
import KelasImage2 from "./assets/img/kelas/kelas-2.jpg";
import KelasImage3 from "./assets/img/kelas/kelas-3.jpg";
import KelasImage4 from "./assets/img/kelas/kelas-4.jpg";
import KelasImage5 from "./assets/img/kelas/kelas-5.jpg";
import KelasImage6 from "./assets/img/kelas/kelas-6.jpg";
import KelasImage7 from "./assets/img/kelas/kelas-7.jpg";
import KelasImage8 from "./assets/img/kelas/kelas-8.jpg";
import KelasImage9 from "./assets/img/kelas/kelas-9.jpg";

import People1 from "./components/testimonial/people-1.jpg";
import People2 from "./components/testimonial/people-2.jpg";
import People3 from "./components/testimonial/people-3.jpg";

export const navLinks = [
  {
    id: 1,
    path: "home",
    text: "Home",
  },
  {
    id: 2,
    path: "kelas",
    text: "Promo",
  },
  {
    id: 3,
    path: "testimonial",
    text: "Inventory",
  },
  {
    id: 4,
    path: "faq",
    text: "FAQ",
  },
  {
    id: 5,
    path: "syaratketen",
    text: "Syarat & Ketentuan",
  },
];

export const semuaKelas = [
  {
    id: 1,
    image: KelasImage1,
    star1: "fa-solid fa-star",
    star2: "fa-solid fa-star",
    star3: "fa-solid fa-star",
    star4: "fa-solid fa-star",
    star5: "fa-solid fa-star-half-stroke",
    title: "Pulsa",
    price1: "Rp. 13.000",
    price: "Rp. 12.000",
    buy: "Beli Sekarang",
    delay: "1300",
  },
  {
    id: 2,
    image: KelasImage2,
    star1: "fa-solid fa-star",
    star2: "fa-solid fa-star",
    star3: "fa-solid fa-star",
    star4: "fa-solid fa-star",
    star5: "fa-solid fa-star",
    title: "Mobile Legends: Bang Bang",
    price1: "Rp. 20.000",
    price: "Rp. 15.000",
    buy: "Beli Sekarang",
    delay: "1600",
  },
  {
    id: 3,
    image: KelasImage3,
    star1: "fa-solid fa-star",
    star2: "fa-solid fa-star",
    star3: "fa-solid fa-star",
    star4: "fa-solid fa-star",
    star5: "fa-solid fa-star",
    title: "Genshin Impact",
    price1: "Rp. 79.000",
    price: "Rp. 68.000",
    buy: "Beli Sekarang",
    delay: "1900",
  },
  {
    id: 4,
    image: KelasImage4,
    star1: "fa-solid fa-star",
    star2: "fa-solid fa-star",
    star3: "fa-solid fa-star",
    star4: "fa-solid fa-star",
    star5: "fa-solid fa-star",
    title: "Freefire",
    price1: "Rp. 25.000",
    price: "Rp. 21.000",
    buy: "Beli Sekarang",
    delay: "",
  },
  {
    id: 5,
    image: KelasImage5,
    star1: "fa-solid fa-star",
    star2: "fa-solid fa-star",
    star3: "fa-solid fa-star",
    star4: "fa-solid fa-star",
    star5: "fa-solid fa-star",
    title: "Call of Duty Mobile",
    price1: "Rp. 30.000",
    price: "Rp. 20.000",
    buy: "Beli Sekarang",
    delay: "300",
  },
  {
    id: 6,
    image: KelasImage6,
    star1: "fa-solid fa-star",
    star2: "fa-solid fa-star",
    star3: "fa-solid fa-star",
    star4: "fa-solid fa-star",
    star5: "fa-solid fa-star",
    title: "Pubg Mobile",
    price1: "Rp. 60.000",
    price: "Rp. 50.000",
    buy: "Beli Sekarang",
    delay: "600",
  },
  {
    id: 7,
    image: KelasImage7,
    star1: "fa-solid fa-star",
    star2: "fa-solid fa-star",
    star3: "fa-solid fa-star",
    star4: "fa-solid fa-star",
    star5: "fa-solid fa-star-half-stroke",
    title: "Honkai: Star Rail",
    price1: "Rp. 21.000",
    price: "Rp. 17.000",
    buy: "Beli Sekarang",
    delay: "",
  },
  {
    id: 8,
    image: KelasImage8,
    star1: "fa-solid fa-star",
    star2: "fa-solid fa-star",
    star3: "fa-solid fa-star",
    star4: "fa-solid fa-star",
    star5: "fa-solid fa-star-half-stroke",
    title: "Harry Potter: Magic Awakened",
    price1: "Rp. 21.000",
    price: "Rp. 30.000",
    buy: "Beli Sekarang",
    delay: "300",
  },
  {
    id: 9,
    image: KelasImage9,
    star1: "fa-solid fa-star",
    star2: "fa-solid fa-star",
    star3: "fa-solid fa-star",
    star4: "fa-solid fa-star",
    star5: "fa-solid fa-star-half-stroke",
    title: "Tower of Fantasy",
    price1: "Rp. 249.000",
    price: "Rp. 175.300",
    buy: "Beli Sekarang",
    delay: "600",
  },
];

export const kelasTerbaru = [
  {
    id: 1,
    image: KelasImage1,
    star1: "fa-solid fa-star",
    star2: "fa-solid fa-star",
    star3: "fa-solid fa-star",
    star4: "fa-solid fa-star",
    star5: "fa-solid fa-star-half-stroke",
    title: "Pulsa",
    price1: "Rp. 13.000",
    price: "Rp. 12.000",
    buy: "Beli Sekarang",
    delay: "",
  },
  {
    id: 2,
    image: KelasImage2,
    star1: "fa-solid fa-star",
    star2: "fa-solid fa-star",
    star3: "fa-solid fa-star",
    star4: "fa-solid fa-star",
    star5: "fa-solid fa-star",
    title: "Mobile Legends",
    price1: "Rp. 20.000",
    price: "Rp. 15.000",
    buy: "Beli Sekarang",
    delay: "200",
  },
  {
    id: 3,
    image: KelasImage3,
    star1: "fa-solid fa-star",
    star2: "fa-solid fa-star",
    star3: "fa-solid fa-star",
    star4: "fa-solid fa-star",
    star5: "fa-solid fa-star",
    title: "Genshin Impact",
    price1: "Rp. 79.000",
    price: "Rp. 68.000",
    buy: "Beli Sekarang",
    delay: "400",
  },
  {
    id: 4,
    image: KelasImage4,
    star1: "fa-solid fa-star",
    star2: "fa-solid fa-star",
    star3: "fa-solid fa-star",
    star4: "fa-solid fa-star",
    star5: "fa-solid fa-star",
    title: "Freefire",
    price1: "Rp. 25.000",
    price: "Rp. 21.000",
    buy: "Beli Sekarang",
    delay: "",
  },
  {
    id: 5,
    image: KelasImage5,
    star1: "fa-solid fa-star",
    star2: "fa-solid fa-star",
    star3: "fa-solid fa-star",
    star4: "fa-solid fa-star",
    star5: "fa-solid fa-star",
    title: "Call of Duty Mobile",
    price1: "Rp. 30.000",
    price: "Rp. 20.000",
    buy: "Beli Sekarang",
    delay: "200",
  },
  {
    id: 6,
    image: KelasImage6,
    star1: "fa-solid fa-star",
    star2: "fa-solid fa-star",
    star3: "fa-solid fa-star",
    star4: "fa-solid fa-star",
    star5: "fa-solid fa-star",
    title: "PUBG Mobile",
    price1: "Rp. 60.000",
    price: "Rp. 50.000",
    buy: "Beli Sekarang",
    delay: "400",
  },
];

export const testimonial = [
  {
    id: 1,
    desc: "Terima kasih atas kemudahan dan kecepatan top up di website Anda! Saya sangat puas dengan layanannya.",
    image: People1,
    name: "People 1",
    skill: "Siswa Rekayasa Perangkat Lunak",
  },
  {
    id: 2,
    desc: "Top up di website Anda sangat mudah dan praktis. Saya akan selalu menggunakan website ini untuk top up pulsa saya.",
    image: People2,
    name: "People 2",
    skill: "Siswa Rekayasa Perangkat Lunak",
  },
  {
    id: 3,
    desc: "Website Anda sangat user-friendly dan proses top upnya sangat cepat. Saya sangat senang dengan pengalaman saya.",
    image: People3,
    name: "People 3",
    skill: "Siswa Rekayasa Perangkat Lunak",
  },
  {
    id: 4,
    desc: "Saya sangat terkesan dengan website top up Anda. Semuanya berjalan dengan lancar dan tanpa masalah.",
    image: People1,
    name: "People 4",
    skill: "Siswa Rekayasa Perangkat Lunak",
  },
  {
    id: 5,
    desc: "Top up di website Anda adalah solusi terbaik untuk kebutuhan pulsa saya. Saya sangat merekomendasikan website ini kepada semua orang.",
    image: People2,
    name: "People 5",
    skill: "Siswa Rekayasa Perangkat Lunak",
  },
  {
    id: 6,
    desc: "Cepat dan gak ribet! Top up di website ini beneran hemat waktu saya.  Bakal jadi langganan nih!",
    image: People3,
    name: "People 6",
    skill: "Siswa Rekayasa Perangkat Lunak",
  },
  {
    id: 7,
    desc: "Senang banget nemuin website top up yang gampang dipake kayak gini.  Cocok buat orang awam kayak saya. Makasih ya! ",
    image: People1,
    name: "People 7",
    skill: "Siswa Rekayasa Perangkat Lunak",
  },
  {
    id: 8,
    desc: "Top up lancar, dapet pulsa langsung masuk!  Website terpercaya banget.  Puas deh pokoknya!",
    image: People2,
    name: "People 8",
    skill: "Siswa Rekayasa Perangkat Lunak",
  },
  {
    id: 9,
    desc: "Website Ready top up keren abis!  Prosesnya cepet, tampilannya kece, banyak promo pula.",
    image: People3,
    name: "People 9",
    skill: "Siswa Rekayasa Perangkat Lunak",
  },
];

export const dataSwiper = [
  {
    id: 1,
    desc: "Terima kasih atas kemudahan dan kecepatan top up di website Anda! Saya sangat puas dengan layanannya.",
    image: People1,
    name: "People 1",
    skill: "Siswa Rekayasa Perangkat Lunak",
  },
  {
    id: 2,
    desc: "Top up di website Anda sangat mudah dan praktis. Saya akan selalu menggunakan website ini untuk top up pulsa saya.",
    image: People2,
    name: "People 2",
    skill: "Siswa Rekayasa Perangkat Lunak",
  },
  {
    id: 3,
    desc: "Website Anda sangat user-friendly dan proses top upnya sangat cepat. Saya sangat senang dengan pengalaman saya.",
    image: People3,
    name: "People 3",
    skill: "Siswa Rekayasa Perangkat Lunak",
  },
  {
    id: 4,
    desc: "Saya sangat terkesan dengan website top up Anda. Semuanya berjalan dengan lancar dan tanpa masalah.",
    image: People1,
    name: "People 4",
    skill: "Siswa Rekayasa Perangkat Lunak",
  },
  {
    id: 5,
    desc: "Top up di website Anda adalah solusi terbaik untuk kebutuhan pulsa saya. Saya sangat merekomendasikan website ini kepada semua orang.",
    image: People2,
    name: "People 5",
    skill: "Siswa Rekayasa Perangkat Lunak",
  },
  {
    id: 6,
    desc: "Cepat dan gak ribet! Top up di website ini beneran hemat waktu saya.  Bakal jadi langganan nih!",
    image: People3,
    name: "People 6",
    skill: "Siswa Rekayasa Perangkat Lunak",
  },
];

export const faq = [
  {
    id: 1,
    eventKey: 0,
    title: "Apa saja metode pembayaran yang tersedia untuk top up??",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id estlaborum.",
  },
  {
    id: 2,
    eventKey: 1,
    title: "Berapa lama waktu yang dibutuhkan untuk top up?",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id estlaborum.",
  },
  {
    id: 3,
    eventKey: 2,
    title: "Apakah ada biaya tambahan untuk top up?",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id estlaborum.",
  },
  {
    id: 4,
    eventKey: 3,
    title: "Bagaimana cara memastikan top up saya berhasil?",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id estlaborum.",
  },
  {
    id: 5,
    eventKey: 4,
    title: "Apa yang harus saya lakukan jika top up saya gagal?",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id estlaborum.",
  },
  {
    id: 6,
    eventKey: 5,
    title: "Apakah aman untuk top up online?",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id estlaborum.",
  },
  {
    id: 7,
    eventKey: 6,
    title: "Apa saja layanan yang bisa saya top up?",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id estlaborum.",
  },
  {
    id: 8,
    eventKey: 7,
    title: "Apakah ada promo atau diskon untuk top up?",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id estlaborum.",
  },
];

